services:
  ei-video-obj-detection-runner:
    user: 1000:1000
    devices:
    - /dev/video0
    - /dev/video1
    - /dev/video2
    - /dev/video3
    - /dev/snd
    - /dev/dri
    group_add:
    - dialout
    - video
    - audio
    - render
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.path: /home/arduino/.local/share/arduino-app-cli/examples/video-generic-object-detection
    environment:
      APP_HOME: /home/arduino/.local/share/arduino-app-cli/examples/video-generic-object-detection
      BIND_ADDRESS: 0.0.0.0
      CUSTOM_MODEL_PATH: /home/arduino/.arduino-bricks/ei-models
      EI_OBJ_DETECTION_MODEL: /models/ootb/ei/yolo-x-nano.eim
      HOST_IP: 192.168.1.91
      VIDEO_DEVICE: /dev/video2
