name: Robot Joystick Control
icon: 🤖
description: Control de robot de dos motores mediante joystick web con visualización de PWM y sensores
bricks:
  - arduino:video_object_detection:
      model: face-detection
  - arduino:web_ui

